[[pages]]
path = "app.py"
name = "market octopus"

[[pages]]
path = "other_pages/intent_classification_demo.py"
name = "intent classification demo"

[[pages]]
path = "other_pages/investment_bank.py"
name = "investment bank"

[[pages]]
path = "other_pages/news_demo.py"
name = "news demo"

[[pages]]
path = "other_pages/final_demo.py"
name = "final demo"
