[[pages]]
path = "app.py"
name = "market octopus"

[[pages]]
path = "other_pages/intent_classification_demo.py"
name = "intent classification demo"

[[pages]]
path = "other_pages/news_demo.py"
name = "news demo"
